FROM debian:stretch

# Install Azure CLI
RUN apt-get update -y
RUN apt-get -y install git curl wget #apt-transport-https 

ARG BUNDLE_DIR
COPY . $BUNDLE_DIR

#Install Helm 3
RUN wget https://get.helm.sh/helm-v3.0.0-rc.2-linux-amd64.tar.gz
RUN tar -zxvf helm-v3.0.0-rc.2-linux-amd64.tar.gz
RUN mv linux-amd64/helm /usr/local/bin/helm